mock_orders = [
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-01-28 06:42:52",
    "rs_sku": "CIN_T9QOS75_BURGUNDY",
    "rs_simple_sku": "CIN_T9QOS75_BURGUNDY-38",
    "product_name": "Burgundy Tie Front Dress",
    "manufacturer": "c(inch)",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BURGUNDY",
    "size": 38
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-01-28 06:42:52",
    "rs_sku": "DAI_6165_BLUE",
    "rs_simple_sku": "DAI_6165_BLUE-18",
    "product_name": "Ladies  Pink & Blue Floral Inspired Pants",
    "manufacturer": "Daily Finery",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLUE",
    "size": 18
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-01-28 06:42:52",
    "rs_sku": "STY_JCHI17849_BLACK",
    "rs_simple_sku": "STY_JCHI17849_BLACK-ONESIZE",
    "product_name": "Black Check Headband",
    "manufacturer": "Styleloft",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": "One Size"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "EDI_U9K9614_BLACK",
    "rs_simple_sku": "EDI_U9K9614_BLACK-38",
    "product_name": "Black Kaftan Lounge Dress",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLACK",
    "size": 38
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "STY_3UP7TEB_BLACK",
    "rs_simple_sku": "STY_3UP7TEB_BLACK-38",
    "product_name": "Black Corset Sweater Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLACK",
    "size": 38
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "EDI_E69N79K_RED",
    "rs_simple_sku": "EDI_E69N79K_RED-40",
    "product_name": "Red Fit And Flare Dress With Draw Chord",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "RED",
    "size": 40
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "SOV_S6405_NUDE",
    "rs_simple_sku": "SOV_S6405_NUDE-8",
    "product_name": "Nude Rina Flip Flops",
    "manufacturer": "Soviet",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "NUDE",
    "size": 8
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "TOM_TTL60502_FUSCHIA",
    "rs_simple_sku": "TOM_TTL60502_FUSCHIA-8",
    "product_name": "Ladies Fuschia Lace Up Sneaker",
    "manufacturer": "TomTom",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "FUSCHIA",
    "size": 8
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "STY_YBH9C53_KHAKIGREEN",
    "rs_simple_sku": "STY_YBH9C53_KHAKIGREEN-32",
    "product_name": "Green Pixel Camo Cargo Shorts",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "KHAKIGREEN",
    "size": 32
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-02-28 17:55:03",
    "rs_sku": "ONE_PSM2860SC1_RED",
    "rs_simple_sku": "ONE_PSM2860SC1_RED-S",
    "product_name": "Red Base 2 Tee",
    "manufacturer": "O'Neill",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "S"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-06-04 06:07:57",
    "rs_sku": "SOV_S5709_BLACK",
    "rs_simple_sku": "SOV_S5709_BLACK-8",
    "product_name": "Mens Black Raptor Sneakers",
    "manufacturer": "Soviet",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLACK",
    "size": 8
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-07-08 16:21:05",
    "rs_sku": "GUE_C56020_DKNBLU",
    "rs_simple_sku": "GUE_C56020_DKNBLU-XS",
    "product_name": "Ladies Dark Blue Vine Tri Tee",
    "manufacturer": "GUESS",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLUE",
    "size": "XS"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-08-05 13:26:18",
    "rs_sku": "GCO_U13BB03_NAVY",
    "rs_simple_sku": "GCO_U13BB03_NAVY-34",
    "product_name": "Navy Shift Dress",
    "manufacturer": "G-Couture",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLUE",
    "size": 34
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-09-13 06:25:25",
    "rs_sku": "MOD_9E68D63_OFFWHITE",
    "rs_simple_sku": "MOD_9E68D63_OFFWHITE-ONESIZE",
    "product_name": "Ladies White Bucket Handbag Off",
    "manufacturer": "Moda Scapa",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "OFFWHITE",
    "size": "One Size"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2019-09-13 08:25:20",
    "rs_sku": "MOD_9E68D63_OFFWHITE",
    "rs_simple_sku": "MOD_9E68D63_OFFWHITE-ONESIZE",
    "product_name": "Ladies White Bucket Handbag Off",
    "manufacturer": "Moda Scapa",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "OFFWHITE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-01-18 15:25:44",
    "rs_sku": "TRE_140432_BLANK",
    "rs_simple_sku": "TRE_140432_BLANK-L",
    "product_name": "Teal & Grey Chevron Socks",
    "manufacturer": "Tread + Miller",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-01-18 15:25:44",
    "rs_sku": "TRE_141654_BLANK",
    "rs_simple_sku": "TRE_141654_BLANK-L",
    "product_name": "Bone & Navy SA Flag Socks",
    "manufacturer": "Tread + Miller",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-01-21 09:18:21",
    "rs_sku": "ASI_1011A006_020",
    "rs_simple_sku": "ASI_1011A006_020-9",
    "product_name": "Mens Glacier Grey & Black Dynamis 2 Running Shoes",
    "manufacturer": "Asics",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": 20,
    "size": 9
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-01-21 09:18:21",
    "rs_sku": "STY_RWT040_BLACK",
    "rs_simple_sku": "STY_RWT040_BLACK-L",
    "product_name": "Black Maxi Wrap Dress",
    "manufacturer": "Styleloft",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLACK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-01-28 08:16:16",
    "rs_sku": "EVE_DWELZ034CAM_CAMO",
    "rs_simple_sku": "EVE_DWELZ034CAM_CAMO-10",
    "product_name": "Ladies Camo Full Length Leggings",
    "manufacturer": "Everlast",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "CAMO",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-02-06 08:21:59",
    "rs_sku": "EDI_51D2S76_BLACK",
    "rs_simple_sku": "EDI_51D2S76_BLACK-34",
    "product_name": "Black Short Sleeve Dress With Frills",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLACK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-02-06 08:21:59",
    "rs_sku": "EDI_R54PJH1_MULTICOLOUR",
    "rs_simple_sku": "EDI_R54PJH1_MULTICOLOUR-6",
    "product_name": "Multi-Colour Slingback Sandals",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "MULTICOLOUR",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-02-06 08:21:59",
    "rs_sku": "STY_Z46479M_MAGENTA",
    "rs_simple_sku": "STY_Z46479M_MAGENTA-34",
    "product_name": "Magenta Asymmetrical Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "MAGENTA",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-02-21 11:07:15",
    "rs_sku": "RUB_41887001_BLANK",
    "rs_simple_sku": "RUB_41887001_BLANK-6",
    "product_name": "Black Everyday Scarlett Slides",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLANK",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-02-21 11:07:15",
    "rs_sku": "TRE_140490_BLANK",
    "rs_simple_sku": "TRE_140490_BLANK-L",
    "product_name": "Blue & Black Ping Pong Socks",
    "manufacturer": "Tread + Miller",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-03-18 08:09:42",
    "rs_sku": "COT_66059818_BLANK",
    "rs_simple_sku": "COT_66059818_BLANK-34B",
    "product_name": "Coral Medium Impact Contour Sports Bra",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "34B"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-03-19 07:35:17",
    "rs_sku": "EDI_7KERMA7_CAMEL",
    "rs_simple_sku": "EDI_7KERMA7_CAMEL-M",
    "product_name": "Ladies Camel Wide Collar Trench Coat",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BROWN",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-01 08:07:36",
    "rs_sku": "HER_10810004_NAVY",
    "rs_simple_sku": "HER_10810004_NAVY-ONESIZE",
    "product_name": "Mens Navy Dean Cap",
    "manufacturer": "Herschel Supply Co.",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "NAVY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-01 08:07:36",
    "rs_sku": "HER_10470034_NAVY",
    "rs_simple_sku": "HER_10470034_NAVY-ONESIZE",
    "product_name": "Mens Black Debossed Whaler Mesh Cap",
    "manufacturer": "Herschel Supply Co.",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "NAVY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-01 08:07:36",
    "rs_sku": "CHA_FYUM300BSICIC_COCONUTICE",
    "rs_simple_sku": "CHA_FYUM300BSICIC_COCONUTICE-ONESIZE",
    "product_name": "Coconut Ice Body Silk 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "COCONUTICE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-01 08:07:36",
    "rs_sku": "CHA_FYUM300BSIWBL_WANTONBLUEBERRY",
    "rs_simple_sku": "CHA_FYUM300BSIWBL_WANTONBLUEBERRY-ONESIZE",
    "product_name": "Wanton Blueberry Body Silk 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "WANTONBLUEBERRY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-01 08:07:36",
    "rs_sku": "CHA_FYUM300BUBVBE_VERYBERRY",
    "rs_simple_sku": "CHA_FYUM300BUBVBE_VERYBERRY-ONESIZE",
    "product_name": "Very Berry Bubbles 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "VERYBERRY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-04 08:27:29",
    "rs_sku": "STY_JCHI17898_RED",
    "rs_simple_sku": "STY_JCHI17898_RED-S",
    "product_name": "Red Floral Wrap Top",
    "manufacturer": "Styleloft",
    "gender": "BLANK",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "S"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-04 08:27:29",
    "rs_sku": "CRA_47916_BLANK",
    "rs_simple_sku": "CRA_47916_BLANK-ONESIZE",
    "product_name": "Tarocco Orange Hand Therapy 25g",
    "manufacturer": "Crabtree & Evelyn",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-25 10:41:14",
    "rs_sku": "EDI_T7AX3G9_BLACK",
    "rs_simple_sku": "EDI_T7AX3G9_BLACK-34",
    "product_name": "Black Sleeve Detail Blouse",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLACK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-04-25 10:41:14",
    "rs_sku": "EDI_65Y57P3_BEIGE",
    "rs_simple_sku": "EDI_65Y57P3_BEIGE-32",
    "product_name": "Beige Lightweight Puffer Jacket",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BEIGE",
    "size": 32
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-05-14 08:12:45",
    "rs_sku": "EDI_44X76W9_BLACK",
    "rs_simple_sku": "EDI_44X76W9_BLACK-6",
    "product_name": "Black Marike Moccasins",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLACK",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-05-14 08:12:45",
    "rs_sku": "STY_8A769TJ_RED",
    "rs_simple_sku": "STY_8A769TJ_RED-32",
    "product_name": "Red Drape Detail Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "RED",
    "size": 32
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-05-31 10:32:59",
    "rs_sku": "JEK_4329_MUD",
    "rs_simple_sku": "JEK_4329_MUD-ONESIZE",
    "product_name": "Brown Woodstock 15' Laptop Folder",
    "manufacturer": "Jekyll & Hide",
    "gender": "UNISEX",
    "product_size_attribute": "Accessories",
    "rs_colour": "BROWN",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-05-31 10:32:59",
    "rs_sku": "EVE_SAELT067BLC_BLANK",
    "rs_simple_sku": "EVE_SAELT067BLC_BLANK-L",
    "product_name": "Ladies Black T-shirt",
    "manufacturer": "Everlast",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-06-26 08:05:50",
    "rs_sku": "STY_DLD9D9T_BLACK",
    "rs_simple_sku": "STY_DLD9D9T_BLACK-34",
    "product_name": "Black Racing Stripe Leggings",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-06-26 08:05:50",
    "rs_sku": "STY_BG161IP_BLACK",
    "rs_simple_sku": "STY_BG161IP_BLACK-32",
    "product_name": "Ladies Black Push Up Jeans",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACK",
    "size": 32
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-06-26 08:05:50",
    "rs_sku": "STY_3A6SX95_PALEBLUE",
    "rs_simple_sku": "STY_3A6SX95_PALEBLUE-M",
    "product_name": "Ladies Blue Oversized Jersey",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLUE",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-11 11:40:48",
    "rs_sku": "CHA_FYUM300BFCIC_COCONUTICE",
    "rs_simple_sku": "CHA_FYUM300BFCIC_COCONUTICE-ONESIZE",
    "product_name": "Coconut Ice Body Food 300g",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "COCONUTICE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-11 11:40:48",
    "rs_sku": "FAL_51310812_BURGUNDY",
    "rs_simple_sku": "FAL_51310812_BURGUNDY-ONESIZE",
    "product_name": "Mens Burgundy Argyle Socks",
    "manufacturer": "Falke Eurosocks",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BURGUNDY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-11 11:40:48",
    "rs_sku": "STA_X7437KJ_BLUE",
    "rs_simple_sku": "STA_X7437KJ_BLUE-L",
    "product_name": "Blue Sparkle Socks",
    "manufacturer": "Stance",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLUE",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-11 11:40:48",
    "rs_sku": "STA_NXU8C9V_ORANGE",
    "rs_simple_sku": "STA_NXU8C9V_ORANGE-L",
    "product_name": "Orange Icon Anthem Socks",
    "manufacturer": "Stance",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "ORANGE",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-25 08:50:40",
    "rs_sku": "EVE_SAELT067CRM_BLANK",
    "rs_simple_sku": "EVE_SAELT067CRM_BLANK-L",
    "product_name": "Ladies Coral & Black T-shirt",
    "manufacturer": "Everlast",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-07-25 08:50:40",
    "rs_sku": "POL_P6002015111000403_GREY",
    "rs_simple_sku": "POL_P6002015111000403_GREY-L",
    "product_name": "Mens Grey Crew Neck Melange Pull Over",
    "manufacturer": "Polo",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "GREY",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-06 14:33:30",
    "rs_sku": "THE_CCW4S15_RAVEGREEN",
    "rs_simple_sku": "THE_CCW4S15_RAVEGREEN-L",
    "product_name": "Ladies Rave Green GTD Tee",
    "manufacturer": "The North Face",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "GREEN",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:16",
    "rs_sku": "FOO_FWL00363BGBGA0_BLANK",
    "rs_simple_sku": "FOO_FWL00363BGBGA0_BLANK-6",
    "product_name": "Ladies Beige Taraji Flatform Sandal",
    "manufacturer": "Footwork",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLANK",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:16",
    "rs_sku": "RUB_42152803_BLANK",
    "rs_simple_sku": "RUB_42152803_BLANK-ONESIZE",
    "product_name": "H20 Glow Face Mask",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "RED",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:16",
    "rs_sku": "COT_200644703_BLANK",
    "rs_simple_sku": "COT_200644703_BLANK-M",
    "product_name": "Ladies Navy Square Neck Blouse",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:16",
    "rs_sku": "EDI_L723Y6I_MIDPINK",
    "rs_simple_sku": "EDI_L723Y6I_MIDPINK-34",
    "product_name": "Pink T-Shirt With Frilly Lace Sleeves",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "MIDPINK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:53",
    "rs_sku": "FOO_FWL00363BGBGA0_BLANK",
    "rs_simple_sku": "FOO_FWL00363BGBGA0_BLANK-6",
    "product_name": "Ladies Beige Taraji Flatform Sandal",
    "manufacturer": "Footwork",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLANK",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:53",
    "rs_sku": "COT_200644703_BLANK",
    "rs_simple_sku": "COT_200644703_BLANK-M",
    "product_name": "Ladies Navy Square Neck Blouse",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-23 08:09:53",
    "rs_sku": "EDI_L723Y6I_MIDPINK",
    "rs_simple_sku": "EDI_L723Y6I_MIDPINK-34",
    "product_name": "Pink T-Shirt With Frilly Lace Sleeves",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "MIDPINK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-08-06 14:33:30",
    "rs_sku": "THE_CCW4_RAVEGREEN",
    "rs_simple_sku": "THE_CCW4_RAVEGREEN-L",
    "product_name": "Ladies Rave Green GTD Tee",
    "manufacturer": "The North Face",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "RAVEGREEN",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-03 11:21:11",
    "rs_sku": "PRI_MC0167_NAVY",
    "rs_simple_sku": "PRI_MC0167_NAVY-ONESIZE",
    "product_name": "Navy Bob Beanie",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLUE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-03 11:21:11",
    "rs_sku": "DAI_SCKNTM128435_NAVY",
    "rs_simple_sku": "DAI_SCKNTM128435_NAVY-ONESIZE",
    "product_name": "Mens Navy Winter Warmer Scarf",
    "manufacturer": "Daily Finery",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "NAVY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-27 14:56:57",
    "rs_sku": "COT_66773407_BLANK",
    "rs_simple_sku": "COT_66773407_BLANK-M",
    "product_name": "Leopard Sporty Femme Bralette",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-27 14:56:57",
    "rs_sku": "COT_66467336_BLANK",
    "rs_simple_sku": "COT_66467336_BLANK-S",
    "product_name": "Moonlight Mauve Cindy Brazilian Briefs",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "S"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-27 14:56:57",
    "rs_sku": "COT_66694815_BLANK",
    "rs_simple_sku": "COT_66694815_BLANK-S",
    "product_name": "Yellow Jojo High Waist Bottoms",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "S"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2019-09-27 14:56:57",
    "rs_sku": "COT_66773409_BLANK",
    "rs_simple_sku": "COT_66773409_BLANK-M",
    "product_name": "Rose Sporty Femme Bralette",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLANK",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2019-04-16 15:56:40",
    "rs_sku": "SUP_2750LINUSLINEN_PALEGREY",
    "rs_simple_sku": "SUP_2750LINUSLINEN_PALEGREY-4",
    "product_name": "Pale Grey Classic Italian Canvas Sneakers",
    "manufacturer": "Superga",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "PALEGREY",
    "size": 4
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2019-06-02 14:24:37",
    "rs_sku": "JAC_12117633_BLACK",
    "rs_simple_sku": "JAC_12117633_BLACK-8",
    "product_name": "Black Vision Mixed Sneakers",
    "manufacturer": "JACK & JONES",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLACK",
    "size": 8
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2019-07-31 19:01:03",
    "rs_sku": "DAI_C774_BLACK",
    "rs_simple_sku": "DAI_C774_BLACK-M",
    "product_name": "Mens Black Hooded Outerwear Jacket",
    "manufacturer": "Daily Finery",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BLACK",
    "size": "M"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-02-06 14:19:45",
    "rs_sku": "VIC_AVOL601407B_BLACK",
    "rs_simple_sku": "VIC_AVOL601407B_BLACK-XL",
    "product_name": "Black Extra Large Case",
    "manufacturer": "Victorinox",
    "gender": "BLANK",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-02-21 10:47:58",
    "rs_sku": "SOV_S7020_WHITE",
    "rs_simple_sku": "SOV_S7020_WHITE-6",
    "product_name": "White Simmons Sneakers",
    "manufacturer": "Soviet",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "WHITE",
    "size": 6
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-02-23 10:41:49",
    "rs_sku": "SOV_878TJ6L_MIDBROWN",
    "rs_simple_sku": "SOV_878TJ6L_MIDBROWN-10",
    "product_name": "Mens Mid Brown Skywalker Lace Up Shoes",
    "manufacturer": "Soviet",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "MIDBROWN",
    "size": 10
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-01 16:08:29",
    "rs_sku": "NEW_WL373KSP_BLACK",
    "rs_simple_sku": "NEW_WL373KSP_BLACK-6",
    "product_name": "Black 70s Classic Running Sneakers",
    "manufacturer": "New Balance",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLACK",
    "size": 6
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-19 08:02:14",
    "rs_sku": "CIN_QO8A34D_PALEGREY",
    "rs_simple_sku": "CIN_QO8A34D_PALEGREY-30",
    "product_name": "Grey Zip Detail Sweater Dress",
    "manufacturer": "c(inch)",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "PALEGREY",
    "size": 30
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-19 08:02:14",
    "rs_sku": "EDI_MT113Q9_DARKPINK",
    "rs_simple_sku": "EDI_MT113Q9_DARKPINK-S",
    "product_name": "Pink Round Neckline Pullover Jersey",
    "manufacturer": "edit",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "DARKPINK",
    "size": "S"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-23 08:06:01",
    "rs_sku": "FOR_JS049200_MULTICOLOUR",
    "rs_simple_sku": "FOR_JS049200_MULTICOLOUR-8",
    "product_name": "Paradise Punch Brandy Bardot Linen Jumpsuit",
    "manufacturer": "Forever New",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "MULTICOLOUR",
    "size": 8
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-25 09:12:43",
    "rs_sku": "ONL_48C3E8O_PALEPINK",
    "rs_simple_sku": "ONL_48C3E8O_PALEPINK-2XL",
    "product_name": "Pale Pink Coin Trucker Denim Jacket",
    "manufacturer": "Only & Sons",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "PALEPINK",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-25 09:12:43",
    "rs_sku": "ONL_QZ6W3W8_STONEBEIGE",
    "rs_simple_sku": "ONL_QZ6W3W8_STONEBEIGE-36W34L",
    "product_name": "Stone Cropped Chino Slim Fit Pants",
    "manufacturer": "Only & Sons",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "STONEBEIGE",
    "size": "36W34L"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-03-25 09:12:43",
    "rs_sku": "ONL_676U88X_BLACK",
    "rs_simple_sku": "ONL_676U88X_BLACK-34W32L",
    "product_name": "Black Cam Cropped Slim Chino Pants",
    "manufacturer": "Only & Sons",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACK",
    "size": "34W32L"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MTA258_PINK",
    "rs_simple_sku": "PRI_MTA258_PINK-2XL",
    "product_name": "Pink Teddy Tailored Shirt",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "PINK",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MST192_NAVY",
    "rs_simple_sku": "PRI_MST192_NAVY-XL",
    "product_name": "Navy Flint Styled Shirt",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "NAVY",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MBE267_TANN",
    "rs_simple_sku": "PRI_MBE267_TANN-38",
    "product_name": "Tan Hewitt Belt",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "TANN",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "POL_S18EPG161_NAVY",
    "rs_simple_sku": "POL_S18EPG161_NAVY-38",
    "product_name": "Mens Navy Leather Belt",
    "manufacturer": "Polo Belts",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLUE",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MBE284_BROW",
    "rs_simple_sku": "PRI_MBE284_BROW-38",
    "product_name": "Brown Ron Casual Belt",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BROW",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MSH086_CORA",
    "rs_simple_sku": "PRI_MSH086_CORA-38",
    "product_name": "Coral Bill Shorts",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "CORA",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MSH086_TOBA",
    "rs_simple_sku": "PRI_MSH086_TOBA-40",
    "product_name": "Tobacco Bill Shorts",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "TOBA",
    "size": 40
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-04-07 13:25:16",
    "rs_sku": "PRI_MSH087_NAVY",
    "rs_simple_sku": "PRI_MSH087_NAVY-40",
    "product_name": "Navy Drake Flat Front Shorts",
    "manufacturer": "Pringle of Scotland",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "NAVY",
    "size": 40
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-05-03 08:21:26",
    "rs_sku": "BEB_BEBE01_NUDE",
    "rs_simple_sku": "BEB_BEBE01_NUDE-6",
    "product_name": "Ladies Black Chunky Ankle Sneaker",
    "manufacturer": "Bebe",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "NUDE",
    "size": 6
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-07-14 22:28:17",
    "rs_sku": "STY_37WB764_BLACK",
    "rs_simple_sku": "STY_37WB764_BLACK-S",
    "product_name": "Ladies Black Studded Leather-Look Biker Jacket",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BLACK",
    "size": "S"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-08-13 13:16:00",
    "rs_sku": "TYP_14364818_BLANK",
    "rs_simple_sku": "TYP_14364818_BLANK-ONESIZE",
    "product_name": "Frenchie Bag Charm",
    "manufacturer": "Typo",
    "gender": "UNISEX",
    "product_size_attribute": "Living & Gifts",
    "rs_colour": "RED",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-08-13 13:16:00",
    "rs_sku": "SHO_772IVP1_BLUE",
    "rs_simple_sku": "SHO_772IVP1_BLUE-06MONTHS",
    "product_name": "Vector Boots L Blue",
    "manufacturer": "ShooShoos",
    "gender": "INFANTS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLUE",
    "size": "0-6 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-08-13 13:16:00",
    "rs_sku": "SOO_5XDTOAD_GREEN",
    "rs_simple_sku": "SOO_5XDTOAD_GREEN-36MONTHS",
    "product_name": "Green Puffer Jacket",
    "manufacturer": "Soobe",
    "gender": "INFANTS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "GREEN",
    "size": "3-6 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-08-13 13:16:00",
    "rs_sku": "STY_HNH9ZU3_BLACK",
    "rs_simple_sku": "STY_HNH9ZU3_BLACK-M",
    "product_name": "Black Biker Jacket With Removable Sleeves",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BLACK",
    "size": "M"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-09-04 12:56:08",
    "rs_sku": "STY_Y2V6281_BLUE",
    "rs_simple_sku": "STY_Y2V6281_BLUE-XL",
    "product_name": "Mens Blue Hooded Puffer Jacket",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BLUE",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-10-08 10:43:09",
    "rs_sku": "ZAX_RAN9863_PALEPINK",
    "rs_simple_sku": "ZAX_RAN9863_PALEPINK-6",
    "product_name": "Pale Pink Tam Sandals",
    "manufacturer": "Zaxy",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "PINK",
    "size": 6
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2019-10-15 09:09:10",
    "rs_sku": "JOY_2OVW465_SILVER",
    "rs_simple_sku": "JOY_2OVW465_SILVER-ONESIZE",
    "product_name": "Silver Transparent Glitter Sling Bag",
    "manufacturer": "Joy Collectables",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "Silver",
    "size": "One Size"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-05-08 17:05:24",
    "rs_sku": "ASI_146617_1179",
    "rs_simple_sku": "ASI_146617_1179-XL",
    "product_name": "Performance Black Lite Stripe Lite-Show Top",
    "manufacturer": "Asics",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": 1179,
    "size": "XL"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-10-10 06:45:50",
    "rs_sku": "KEE_K428205_RED",
    "rs_simple_sku": "KEE_K428205_RED-03MONTHS",
    "product_name": "Red Fabel Grow",
    "manufacturer": "Keedo",
    "gender": "UNISEX",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "0-3 Months"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:45:08",
    "rs_sku": "DAI_L7912_MINT",
    "rs_simple_sku": "DAI_L7912_MINT-2XL",
    "product_name": "Ladies Mint T-shirt",
    "manufacturer": "Daily Finery",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "MINT",
    "size": "2XL"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:45:08",
    "rs_sku": "REV_SINFULNAILPOLISH_GREENOCEAN",
    "rs_simple_sku": "REV_SINFULNAILPOLISH_GREENOCEAN-ONESIZE",
    "product_name": "Green Ocean Sinful Nail Polish",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "GREENOCEAN",
    "size": "One Size"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:45:08",
    "rs_sku": "HOM_136134_BLANK",
    "rs_simple_sku": "HOM_136134_BLANK-20",
    "product_name": "Ladies Pink Danica Wrap Top",
    "manufacturer": "HomeChoice",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": 20
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:45:08",
    "rs_sku": "GCO_AVI3295_ORANGE",
    "rs_simple_sku": "GCO_AVI3295_ORANGE-40",
    "product_name": "Orange Gathered Top",
    "manufacturer": "G-Couture",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "ORANGE",
    "size": 40
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:45:08",
    "rs_sku": "REV_SINFULNAILPOLISH_DREAMON",
    "rs_simple_sku": "REV_SINFULNAILPOLISH_DREAMON-ONESIZE",
    "product_name": "Dream On Sinful Nail Polish",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "DREAMON",
    "size": "One Size"
  },
  {
    "email": "anel.k@runwaysale.co.za",
    "ordered_at": "2018-12-16 13:30:57",
    "rs_sku": "BRO_52L7S377C_TAN",
    "rs_simple_sku": "BRO_52L7S377C_TAN-3",
    "product_name": "Tan Jillian Flat Shoe",
    "manufacturer": "Bronx Woman",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "Tan",
    "size": 3
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-01-19 10:02:10",
    "rs_sku": "MAN_63088813_KHAKI37",
    "rs_simple_sku": "MAN_63088813_KHAKI37-L",
    "product_name": "Khaki Printed Bombay Skirt",
    "manufacturer": "Mango",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "KHAKI37",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-02-02 09:20:59",
    "rs_sku": "NIK_831530010_BLANK",
    "rs_simple_sku": "NIK_831530010_BLANK-L",
    "product_name": "Ladies Black Dry Miler Running Top",
    "manufacturer": "Nike",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-02-02 09:20:59",
    "rs_sku": "HUM_5391521280640_BLANK",
    "rs_simple_sku": "HUM_5391521280640_BLANK-ONESIZE",
    "product_name": "Light to Medium BB Cream 50ML",
    "manufacturer": "Human + Kind",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-02-21 08:09:33",
    "rs_sku": "ASI_110422SA_8091",
    "rs_simple_sku": "ASI_110422SA_8091-L",
    "product_name": "Ladies Blue Purple Short Sleeve Top",
    "manufacturer": "Asics",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": 8091,
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-02-26 12:29:59",
    "rs_sku": "FOR_ISH587_CORAL",
    "rs_simple_sku": "FOR_ISH587_CORAL-10",
    "product_name": "Pacific Coral Lana Frill Sleeve Boxy Blouse",
    "manufacturer": "Forever New",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "CORAL",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-03-07 08:03:56",
    "rs_sku": "NIK_683527010_BLANK",
    "rs_simple_sku": "NIK_683527010_BLANK-L",
    "product_name": "Mens Black Dry Miler Running Top",
    "manufacturer": "Nike",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-03-07 08:03:56",
    "rs_sku": "NIK_683527480_BLANK",
    "rs_simple_sku": "NIK_683527480_BLANK-L",
    "product_name": "Mens Blue Dry Miler Running Top",
    "manufacturer": "Nike",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-03-27 15:12:20",
    "rs_sku": "COT_27002602_CHAMBRAY",
    "rs_simple_sku": "COT_27002602_CHAMBRAY-M",
    "product_name": "Ladies Chambray Vivian Cotton Shirt",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "CHAMBRAY",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-04-09 15:37:24",
    "rs_sku": "REV_BLUSH_MAUVELOUS3",
    "rs_simple_sku": "REV_BLUSH_MAUVELOUS3-ONESIZE",
    "product_name": "Pink Marvelous Powder Blush",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "MAUVELOUS3",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-04-09 15:37:24",
    "rs_sku": "REV_AIRBRUSHEFFECT_NBEIGE005",
    "rs_simple_sku": "REV_AIRBRUSHEFFECT_NBEIGE005-ONESIZE",
    "product_name": "Natural Beige Airbrush Effect Foundation",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "NBEIGE005",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-05-02 08:03:03",
    "rs_sku": "CLA_01136100_BLANK",
    "rs_simple_sku": "CLA_01136100_BLANK-ONESIZE",
    "product_name": "Hydra Quench Cream Mask",
    "manufacturer": "Clarins",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-05-21 15:43:50",
    "rs_sku": "SEA_30776065_ICEBERG",
    "rs_simple_sku": "SEA_30776065_ICEBERG-10",
    "product_name": "Iceberg Wrap Front Bralette",
    "manufacturer": "Seafolly",
    "gender": "LADIES",
    "product_size_attribute": "Swimwear",
    "rs_colour": "Iceberg",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-05-21 15:43:50",
    "rs_sku": "SEA_40241065_ICEBERG",
    "rs_simple_sku": "SEA_40241065_ICEBERG-10",
    "product_name": "Iceberg Goddess Mini Hipster",
    "manufacturer": "Seafolly",
    "gender": "LADIES",
    "product_size_attribute": "Swimwear",
    "rs_colour": "Iceberg",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-06-04 13:10:09",
    "rs_sku": "WOM_59973130_98SEVERAL",
    "rs_simple_sku": "WOM_59973130_98SEVERAL-M",
    "product_name": "Pink & Aqua Bicolour Bikini Bottoms",
    "manufacturer": "Women'secret",
    "gender": "LADIES",
    "product_size_attribute": "Swimwear",
    "rs_colour": "98SEVERAL",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-06-07 08:05:32",
    "rs_sku": "NIK_833056010_BLANK",
    "rs_simple_sku": "NIK_833056010_BLANK-L",
    "product_name": "Ladies Black Power Legend Training Tight",
    "manufacturer": "Nike",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-06-15 10:23:33",
    "rs_sku": "TRA_08525512_BLACK",
    "rs_simple_sku": "TRA_08525512_BLACK-ONESIZE",
    "product_name": "Unisex Black & Orange iSpot Trolley Duffle 70 cm",
    "manufacturer": "Travelite Luggage",
    "gender": "UNISEX",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-07-23 10:15:44",
    "rs_sku": "COT_66584001_BLANK",
    "rs_simple_sku": "COT_66584001_BLANK-L",
    "product_name": "Black Strappy Back Tank Top",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-07-23 10:15:44",
    "rs_sku": "COT_66585001_BLANK",
    "rs_simple_sku": "COT_66585001_BLANK-L",
    "product_name": "Black Knockout Training Shorts",
    "manufacturer": "Cotton On Body",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-07-27 11:24:54",
    "rs_sku": "PIE_BGL00107BKBK_A0",
    "rs_simple_sku": "PIE_BGL00107BKBK_A0-ONESIZE",
    "product_name": "Black Classic Signature Shopper",
    "manufacturer": "Pierre Cardin",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "A0",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-02 09:13:18",
    "rs_sku": "LUN_INFINITY120ML_BLANK",
    "rs_simple_sku": "LUN_INFINITY120ML_BLANK-ONESIZE",
    "product_name": "Infinity Diffuser 120ml",
    "manufacturer": "Lundie & Crowe",
    "gender": "LADIES",
    "product_size_attribute": "Living & Gifts",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-02 09:13:18",
    "rs_sku": "CHA_FYUM300HWACIC_COCONUTICE",
    "rs_simple_sku": "CHA_FYUM300HWACIC_COCONUTICE-ONESIZE",
    "product_name": "Coconut Ice Hand Wash 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "COCONUTICE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-02 09:13:18",
    "rs_sku": "CHA_FYUM300BSICIC_COCONUTICE",
    "rs_simple_sku": "CHA_FYUM300BSICIC_COCONUTICE-ONESIZE",
    "product_name": "Coconut Ice Body Silk 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "COCONUTICE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-15 09:26:51",
    "rs_sku": "STY_RWT011_FORESTGREEN",
    "rs_simple_sku": "STY_RWT011_FORESTGREEN-S",
    "product_name": "Green Bell Sleeve Top",
    "manufacturer": "Styleloft",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "FORESTGREEN",
    "size": "S"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-23 12:17:54",
    "rs_sku": "COT_200248802_CARNATION",
    "rs_simple_sku": "COT_200248802_CARNATION-M",
    "product_name": "Carnation Taylor Flare Rib Pullover",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "CARNATION",
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-23 12:17:54",
    "rs_sku": "NIK_831530100_BLANK",
    "rs_simple_sku": "NIK_831530100_BLANK-XL",
    "product_name": "White Dry Miler Running Top",
    "manufacturer": "Nike",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "XL"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-31 14:49:26",
    "rs_sku": "TRI_3251_04",
    "rs_simple_sku": "TRI_3251_04-S",
    "product_name": "Black Second Skin Longleg Shapewear",
    "manufacturer": "Triumph",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": 4,
    "size": "S"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-08-31 14:49:26",
    "rs_sku": "TRI_3586_879",
    "rs_simple_sku": "TRI_3586_879-M",
    "product_name": "Black & White Mix Seamfree Crop Top",
    "manufacturer": "Triaction",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": 879,
    "size": "M"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-05 09:16:46",
    "rs_sku": "POL_EPG252WYATT_BLACK",
    "rs_simple_sku": "POL_EPG252WYATT_BLACK-42",
    "product_name": "Black Wyatt Leather Belt",
    "manufacturer": "Polo Belts",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": 42
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-05 09:16:46",
    "rs_sku": "FAL_51113185_MANGANESE",
    "rs_simple_sku": "FAL_51113185_MANGANESE-1012",
    "product_name": "Manganese Grid Check Socks",
    "manufacturer": "Falke Eurosocks",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "MANGANESE",
    "size": "12-Oct"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-17 08:16:05",
    "rs_sku": "TOM_5901005_WHITE",
    "rs_simple_sku": "TOM_5901005_WHITE-6",
    "product_name": "Ladies White Low Cut Sneaker",
    "manufacturer": "Tomy Takkies",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "WHITE",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-17 08:16:05",
    "rs_sku": "BAT_5010724527511_TROPICAL",
    "rs_simple_sku": "BAT_5010724527511_TROPICAL-ONESIZE",
    "product_name": "Dry Shampoo All Hair Types Tropical 200ML",
    "manufacturer": "Batiste",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "RED",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-25 08:22:00",
    "rs_sku": "COT_200079808_BLANK",
    "rs_simple_sku": "COT_200079808_BLANK-10",
    "product_name": "Ladies Black & Green Floral Maxi Skirt",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-09-25 08:22:00",
    "rs_sku": "SAM_FG0635_BLANK",
    "rs_simple_sku": "SAM_FG0635_BLANK-ONESIZE",
    "product_name": "H2O Emergency Mask",
    "manufacturer": "Sampar",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-05 08:59:18",
    "rs_sku": "FOR_DR914200_NAVYBLUE",
    "rs_simple_sku": "FOR_DR914200_NAVYBLUE-10",
    "product_name": "Navy Jordan Jacquard Dress",
    "manufacturer": "Forever New",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "NAVYBLUE",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-11 07:51:50",
    "rs_sku": "FOR_DR914200_NAVYBLUE",
    "rs_simple_sku": "FOR_DR914200_NAVYBLUE-8",
    "product_name": "Navy Jordan Jacquard Dress",
    "manufacturer": "Forever New",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "NAVYBLUE",
    "size": 8
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-15 09:50:01",
    "rs_sku": "FOR_DR914200_NAVYBLUE",
    "rs_simple_sku": "FOR_DR914200_NAVYBLUE-10",
    "product_name": "Navy Jordan Jacquard Dress",
    "manufacturer": "Forever New",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "NAVYBLUE",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-24 14:51:03",
    "rs_sku": "BOU_FC28474_3052503573106",
    "rs_simple_sku": "BOU_FC28474_3052503573106-ONESIZE",
    "product_name": "Ivory Perfect CC Cream 30ML",
    "manufacturer": "Bourjois",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": 3052500000000,
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-24 14:51:03",
    "rs_sku": "COT_200082607_BLANK",
    "rs_simple_sku": "COT_200082607_BLANK-10",
    "product_name": "Ladies Floral Mood Indigo Elora  Maxi Skirt",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-30 08:12:07",
    "rs_sku": "DAI_HTFD4F33202_STRAW",
    "rs_simple_sku": "DAI_HTFD4F33202_STRAW-ONESIZE",
    "product_name": "Ladies Straw Fedora Hat",
    "manufacturer": "Daily Finery",
    "gender": "UNISEX",
    "product_size_attribute": "Accessories",
    "rs_colour": "STRAW",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-30 08:12:07",
    "rs_sku": "DAI_BLPUBM22377_BLACK",
    "rs_simple_sku": "DAI_BLPUBM22377_BLACK-L",
    "product_name": "Mens Black Formal Belt",
    "manufacturer": "Daily Finery",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-30 08:12:07",
    "rs_sku": "DAI_HTCP4F55439_NAVY",
    "rs_simple_sku": "DAI_HTCP4F55439_NAVY-ONESIZE",
    "product_name": "Unisex NY Cap",
    "manufacturer": "Daily Finery",
    "gender": "UNISEX",
    "product_size_attribute": "Accessories",
    "rs_colour": "NAVY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-10-31 12:12:40",
    "rs_sku": "COT_200080205_BLANK",
    "rs_simple_sku": "COT_200080205_BLANK-10",
    "product_name": "Purple Kimono Sleeve Maxi Dress",
    "manufacturer": "Cotton On",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLANK",
    "size": 10
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "FEL_W18SET51_CAT",
    "rs_simple_sku": "FEL_W18SET51_CAT-03MONTHS",
    "product_name": "White Cat Bib, Shoe & Hat Set",
    "manufacturer": "Felix & Fiona",
    "gender": "UNISEX",
    "product_size_attribute": "Sets",
    "rs_colour": "CAT",
    "size": "0-3 Months"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "FEL_SHOES_BLUE",
    "rs_simple_sku": "FEL_SHOES_BLUE-03MONTHS",
    "product_name": "Blue Striped Shoes",
    "manufacturer": "Felix & Fiona",
    "gender": "BOYS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLUE",
    "size": "0-3 Months"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "FEL_BIBS_BLUE",
    "rs_simple_sku": "FEL_BIBS_BLUE-ONESIZE",
    "product_name": "Blue Striped Bibs",
    "manufacturer": "Felix & Fiona",
    "gender": "BOYS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLUE",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "PAR_160132149_WHITE",
    "rs_simple_sku": "PAR_160132149_WHITE-36MONTHS",
    "product_name": "Octopus Vest",
    "manufacturer": "Parental Instinct",
    "gender": "KIDS",
    "product_size_attribute": "Tops",
    "rs_colour": "WHITE",
    "size": "3-6 Months"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "LAS_893436002232_BLANK",
    "rs_simple_sku": "LAS_893436002232_BLANK-ONESIZE",
    "product_name": "Brunette Colour Strokes Brow Tint & Lift 8ml",
    "manufacturer": "Lashem",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "RED",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-08 09:47:26",
    "rs_sku": "PAR_160131107_WHITE",
    "rs_simple_sku": "PAR_160131107_WHITE-36MONTHS",
    "product_name": "White Superstar Vest",
    "manufacturer": "Parental Instinct",
    "gender": "KIDS",
    "product_size_attribute": "Tops",
    "rs_colour": "WHITE",
    "size": "3-6 Months"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-16 08:15:48",
    "rs_sku": "SUN_7024_CROCHETSKY",
    "rs_simple_sku": "SUN_7024_CROCHETSKY-36",
    "product_name": "Crochet Sky Ruched Bum Panty",
    "manufacturer": "Sun Love",
    "gender": "LADIES",
    "product_size_attribute": "Swimwear",
    "rs_colour": "CROCHETSKY",
    "size": 36
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-16 08:15:48",
    "rs_sku": "CHA_FYUM300HWAWBL_WANTONBLUEBERRY",
    "rs_simple_sku": "CHA_FYUM300HWAWBL_WANTONBLUEBERRY-ONESIZE",
    "product_name": "Wanton Blueberry Hand Wash 300ml",
    "manufacturer": "Charlotte Rhys",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "WANTONBLUEBERRY",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-19 06:16:39",
    "rs_sku": "CLA_80028007_BLANK",
    "rs_simple_sku": "CLA_80028007_BLANK-ONESIZE",
    "product_name": "Hydra-Quench Collection",
    "manufacturer": "Clarins",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-23 07:15:52",
    "rs_sku": "RUB_41973603_BLANK",
    "rs_simple_sku": "RUB_41973603_BLANK-ONESIZE",
    "product_name": "Rose Gold Party Tassel Earrings",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-23 07:15:52",
    "rs_sku": "RUB_42245202_BLANK",
    "rs_simple_sku": "RUB_42245202_BLANK-6",
    "product_name": "Pink Rose Rex Twist Slides",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLANK",
    "size": 6
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-23 07:15:52",
    "rs_sku": "TRI_3749_251",
    "rs_simple_sku": "TRI_3749_251-L",
    "product_name": "Ambre Blue The Love Hipster Brief",
    "manufacturer": "Triumph",
    "gender": "LADIES",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "Grey",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-24 08:55:45",
    "rs_sku": "VER_10191087_RED",
    "rs_simple_sku": "VER_10191087_RED-L",
    "product_name": "Ladies Red Frill Detail Dress",
    "manufacturer": "Vero Moda",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "RED",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-24 08:55:45",
    "rs_sku": "ONL_15152567_MIDPINK",
    "rs_simple_sku": "ONL_15152567_MIDPINK-L",
    "product_name": "Pink June Boxy Dress",
    "manufacturer": "ONLY",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLANK",
    "size": "L"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-24 08:55:45",
    "rs_sku": "STY_G58N87P_STONE",
    "rs_simple_sku": "STY_G58N87P_STONE-34",
    "product_name": "Ladies Stone High-Waisted Pants",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "NEUTRAL",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-26 08:23:35",
    "rs_sku": "STY_8I2GTPW_FLORAL",
    "rs_simple_sku": "STY_8I2GTPW_FLORAL-34",
    "product_name": "Floral Cross Over Maxi Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "FLORAL",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-26 08:23:35",
    "rs_sku": "STY_S224674_BLACK",
    "rs_simple_sku": "STY_S224674_BLACK-34",
    "product_name": "Ladies Black Skinny Jeans",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-26 08:23:35",
    "rs_sku": "STY_MPA829Q_BEIGE",
    "rs_simple_sku": "STY_MPA829Q_BEIGE-36",
    "product_name": "Beige Floral Casual Shorts",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BEIGE",
    "size": 36
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-11-26 08:23:35",
    "rs_sku": "CIN_6Q11M4F_BLACK",
    "rs_simple_sku": "CIN_6Q11M4F_BLACK-34",
    "product_name": "Black Volume Maxi Skirt",
    "manufacturer": "c(inch)",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACK",
    "size": 34
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-12-05 09:42:01",
    "rs_sku": "ESS_ESSCOSC72142336_BLANK",
    "rs_simple_sku": "ESS_ESSCOSC72142336_BLANK-ONESIZE",
    "product_name": "Closing Night Gel Couture Nail Polish",
    "manufacturer": "Essie",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-12-05 09:42:01",
    "rs_sku": "STY_JCHI17848_BLACK",
    "rs_simple_sku": "STY_JCHI17848_BLACK-ONESIZE",
    "product_name": "Black Scrunchie",
    "manufacturer": "Styleloft",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLACK",
    "size": "One Size"
  },
  {
    "email": "jess.b@runwaysale.co.za",
    "ordered_at": "2018-12-05 09:42:01",
    "rs_sku": "ASI_155244_8098",
    "rs_simple_sku": "ASI_155244_8098-M",
    "product_name": "Ladies Lake Blue Layering SS Top",
    "manufacturer": "Asics",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": 8098,
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-03-02 16:45:57",
    "rs_sku": "DCS_PM9743_MEDIUMSTONEWASH",
    "rs_simple_sku": "DCS_PM9743_MEDIUMSTONEWASH-30",
    "product_name": "Medium Stone Wash Straight Jeans",
    "manufacturer": "DC Shoes",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "MEDIUMSTONEWASH",
    "size": 30
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-03-02 16:45:57",
    "rs_sku": "DCS_ADYS100324_GYB",
    "rs_simple_sku": "DCS_ADYS100324_GYB-8",
    "product_name": "Grey & Black New Jack S Sneakers",
    "manufacturer": "DC Shoes",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "GYB",
    "size": 8
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-05-29 20:28:07",
    "rs_sku": "TIM_9230R_BLANK",
    "rs_simple_sku": "TIM_9230R_BLANK-125",
    "product_name": "Mens Light Brown Earthkeepers Intervale Trail Shoes",
    "manufacturer": "Timberland",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLANK",
    "size": 12.5
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-07-02 12:51:33",
    "rs_sku": "ING_INQ018WHSL_BLANK",
    "rs_simple_sku": "ING_INQ018WHSL_BLANK-ONESIZE",
    "product_name": "Mens White Mount Chronograph Watch",
    "manufacturer": "Ingersoll",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-07-18 18:14:21",
    "rs_sku": "UMB_F80884M262_GREYWHITE",
    "rs_simple_sku": "UMB_F80884M262_GREYWHITE-9",
    "product_name": "Mens Breeze Grey & White Lace Up  Trainer",
    "manufacturer": "Umbro",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "GREYWHITE",
    "size": 9
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-07-18 18:14:21",
    "rs_sku": "ALD_SIGRUNR_96BLACKSYNTHETIC",
    "rs_simple_sku": "ALD_SIGRUNR_96BLACKSYNTHETIC-9",
    "product_name": "Mens Black Sigrun Lace Up Sneakers",
    "manufacturer": "Aldo",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "96BLACKSYNTHETIC",
    "size": 9
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_88U839T_NAVY",
    "rs_simple_sku": "STY_88U839T_NAVY-M",
    "product_name": "Navy Entry Crew Neck Tee",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "NAVY",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_R5IZI84_NAVY",
    "rs_simple_sku": "STY_R5IZI84_NAVY-M",
    "product_name": "Mens Navy Hype Print Tee",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "NAVY",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_NMMXW15_MULTICOLOUR",
    "rs_simple_sku": "STY_NMMXW15_MULTICOLOUR-M",
    "product_name": "Multi-Colour 3-Pack T-Shirts",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "MULTICOLOUR",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_3T33F52_CHARCOAL",
    "rs_simple_sku": "STY_3T33F52_CHARCOAL-M",
    "product_name": "Mens Charcoal Crew Val Sweatshirt",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "Charcoal",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_1N26E5U_BLACK",
    "rs_simple_sku": "STY_1N26E5U_BLACK-M",
    "product_name": "Mens Black Fleek Crew Neck Sweater",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLACK",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_7A86TPG_GREY",
    "rs_simple_sku": "STY_7A86TPG_GREY-M",
    "product_name": "Mens Grey Fleek Crew Neck Sweatshirt",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "GREY",
    "size": "M"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_3S72R6F_RED",
    "rs_simple_sku": "STY_3S72R6F_RED-32",
    "product_name": "Red Cross Back Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "RED",
    "size": 32
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_4FI2O17_WHITE",
    "rs_simple_sku": "STY_4FI2O17_WHITE-5",
    "product_name": "Ladies White Sporty Sneakers",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "WHITE",
    "size": 5
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "STY_G811P18_NEUTRAL",
    "rs_simple_sku": "STY_G811P18_NEUTRAL-4",
    "product_name": "Ladies Neutral High-Top Sneakers",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Shoes",
    "rs_colour": "NEUTRAL",
    "size": 4
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "ONL_15152567_NAVYWHITE",
    "rs_simple_sku": "ONL_15152567_NAVYWHITE-S",
    "product_name": "Navy & White June Boxy Dress",
    "manufacturer": "ONLY",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "NAVYWHITE",
    "size": "S"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_2COL3FX_BLACKANDWHITE",
    "rs_simple_sku": "POP_2COL3FX_BLACKANDWHITE-36MONTHS",
    "product_name": "White Infants Panda Onesie",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "3-6 Months"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_A465OG3_MULTICOLOUR",
    "rs_simple_sku": "POP_A465OG3_MULTICOLOUR-36MONTHS",
    "product_name": "Infants Multi-Colour 2 Piece Hooded Set",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Sets",
    "rs_colour": "MULTI",
    "size": "3-6 Months"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_66Q7WMO_NAVY",
    "rs_simple_sku": "POP_66Q7WMO_NAVY-69MONTHS",
    "product_name": "Navy Infants Printed  Bodysuit",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Tops",
    "rs_colour": "NAVY",
    "size": "6-9 Months"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_656S72N_WHITE",
    "rs_simple_sku": "POP_656S72N_WHITE-36MONTHS",
    "product_name": "White Infants Printed Pull On Pant",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "WHITE",
    "size": "3-6 Months"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_G374B1O_KHAKIGREEN",
    "rs_simple_sku": "POP_G374B1O_KHAKIGREEN-69MONTHS",
    "product_name": "Green Infants Velveteen Joggers",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "6-9 Months"
  },
  {
    "email": "pj.f@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:29:02",
    "rs_sku": "POP_K593B8O_BLACKANDWHITE",
    "rs_simple_sku": "POP_K593B8O_BLACKANDWHITE-912MONTHS",
    "product_name": "Infants White Stripe Pullon Pants",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLACKANDWHITE",
    "size": "9-12 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-01-25 10:11:15",
    "rs_sku": "NIK_855144010_BLANK",
    "rs_simple_sku": "NIK_855144010_BLANK-S",
    "product_name": "Ladies Black Power Running Crop Leggings",
    "manufacturer": "Nike",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "S"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-01-25 10:11:15",
    "rs_sku": "NIK_856836011_BLANK",
    "rs_simple_sku": "NIK_856836011_BLANK-XL",
    "product_name": "Mens Black Flex Running Short",
    "manufacturer": "Nike",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-04-12 15:44:24",
    "rs_sku": "ORI_OPWF7080_NIGHTSHADE",
    "rs_simple_sku": "ORI_OPWF7080_NIGHTSHADE-2XL",
    "product_name": "Nightshade Basic Oxford Shirt",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-04-12 15:44:24",
    "rs_sku": "ORI_OPKF7274_FADEDDENIM",
    "rs_simple_sku": "ORI_OPKF7274_FADEDDENIM-2XL",
    "product_name": "Faded Denim Earl Golfer",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "FADEDDENIM",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-04-12 15:44:24",
    "rs_sku": "ORI_OPHB0001_KELP",
    "rs_simple_sku": "ORI_OPHB0001_KELP-38",
    "product_name": "Kelp Chino Shorts",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "KELP",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-05-07 08:30:53",
    "rs_sku": "NIK_833056010_BLANK",
    "rs_simple_sku": "NIK_833056010_BLANK-XS",
    "product_name": "Ladies Black Power Legend Training Tight",
    "manufacturer": "Nike",
    "gender": "LADIES",
    "product_size_attribute": "Bottoms",
    "rs_colour": "BLANK",
    "size": "XS"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-01 08:19:14",
    "rs_sku": "REV_AIRBRUSHEFFECT_GBEIGE008",
    "rs_simple_sku": "REV_AIRBRUSHEFFECT_GBEIGE008-ONESIZE",
    "product_name": "Golden Beige  Airbrush Effect Foundation",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "GBEIGE008",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-01 08:19:14",
    "rs_sku": "REV_140PHOTOREADY_NUDE",
    "rs_simple_sku": "REV_140PHOTOREADY_NUDE-ONESIZE",
    "product_name": "Nude  Photo Ready Insta Fix",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "NUDE",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-01 08:19:14",
    "rs_sku": "REV_AIRBRUSHEFFECT_NBEIGE005",
    "rs_simple_sku": "REV_AIRBRUSHEFFECT_NBEIGE005-ONESIZE",
    "product_name": "Natural Beige Airbrush Effect Foundation",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "NBEIGE005",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "ORI_OPWF7080_NIGHTSHADE",
    "rs_simple_sku": "ORI_OPWF7080_NIGHTSHADE-2XL",
    "product_name": "Nightshade Basic Oxford Shirt",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "RED",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "ORI_OPKB0557_TRUEBLACK",
    "rs_simple_sku": "ORI_OPKB0557_TRUEBLACK-2XL",
    "product_name": "True Black Winston Golfer",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "TRUEBLACK",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "ORI_OPKF7557_PLUMWINE",
    "rs_simple_sku": "ORI_OPKF7557_PLUMWINE-2XL",
    "product_name": "Plum Wine Raised Rib Golfer",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "PLUMWINE",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "BJO_146227105032_BLUE",
    "rs_simple_sku": "BJO_146227105032_BLUE-XL",
    "product_name": "Mens Blue Lost Short Shorts & Socks Set",
    "manufacturer": "Bjorn Borg",
    "gender": "MENS",
    "product_size_attribute": "Underwear & Sleepwear",
    "rs_colour": "BLUE",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "BJO_154131250001_BLUE",
    "rs_simple_sku": "BJO_154131250001_BLUE-711",
    "product_name": "Mens Blue Body Paint Ankle Socks",
    "manufacturer": "Bjorn Borg",
    "gender": "MENS",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLUE",
    "size": "11-Jul"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "TED_2910173355992006965_BLANK",
    "rs_simple_sku": "TED_2910173355992006965_BLANK-100ML",
    "product_name": "Mens Black Extreme Edt 100ml",
    "manufacturer": "Ted Lapidus",
    "gender": "MENS",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "100 ML"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "BRO_21D7S952A_BLACK",
    "rs_simple_sku": "BRO_21D7S952A_BLACK-11",
    "product_name": "Black Swinford Lace Up Sneaker",
    "manufacturer": "Bronx Men",
    "gender": "MENS",
    "product_size_attribute": "Shoes",
    "rs_colour": "BLACK",
    "size": 11
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-06-12 11:56:43",
    "rs_sku": "ORI_OPHB0001_DARKSAPPHIRE",
    "rs_simple_sku": "ORI_OPHB0001_DARKSAPPHIRE-38",
    "product_name": "Dark Sapphire Chino Shorts",
    "manufacturer": "Original Penguin",
    "gender": "MENS",
    "product_size_attribute": "Bottoms",
    "rs_colour": "DARKSAPPHIRE",
    "size": 38
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-09-14 08:20:48",
    "rs_sku": "OTG_OTG439_PINK",
    "rs_simple_sku": "OTG_OTG439_PINK-S",
    "product_name": "Ladies Pink Rad Race Long Sleeve Tee",
    "manufacturer": "OTG",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "PINK",
    "size": "S"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-09-25 14:44:25",
    "rs_sku": "RUB_41855214_BLANK",
    "rs_simple_sku": "RUB_41855214_BLANK-ONESIZE",
    "product_name": "Mustard Billie Sling Bag",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-09-25 14:44:25",
    "rs_sku": "RUB_42117505_BLANK",
    "rs_simple_sku": "RUB_42117505_BLANK-ONESIZE",
    "product_name": "Multi Splice Soho Print Scarf",
    "manufacturer": "Rubi Shoes",
    "gender": "LADIES",
    "product_size_attribute": "Accessories",
    "rs_colour": "RED",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-10-18 08:12:50",
    "rs_sku": "MAS_MS17905_ORANGE",
    "rs_simple_sku": "MAS_MS17905_ORANGE-32",
    "product_name": "Multi Coloured Button Down dress",
    "manufacturer": "MASTIK",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "ORANGE",
    "size": 32
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-10-22 15:05:43",
    "rs_sku": "REV_AIRBRUSHEFFECT_GBEIGE008",
    "rs_simple_sku": "REV_AIRBRUSHEFFECT_GBEIGE008-ONESIZE",
    "product_name": "Golden Beige  Airbrush Effect Foundation",
    "manufacturer": "Revlon",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "GBEIGE008",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-12 12:42:44",
    "rs_sku": "FEL_SINGLE500SSMAY18_BLUESTRIPE",
    "rs_simple_sku": "FEL_SINGLE500SSMAY18_BLUESTRIPE-03MONTHS",
    "product_name": "Blue Stripe SS Bodyvest",
    "manufacturer": "Felix & Fiona",
    "gender": "BOYS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLUESTRIPE",
    "size": "0-3 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-19 05:58:14",
    "rs_sku": "MUG_12807610_BLANK",
    "rs_simple_sku": "MUG_12807610_BLANK-ONESIZE",
    "product_name": "Alien Extraordinaire 90ml",
    "manufacturer": "Mugler",
    "gender": "LADIES",
    "product_size_attribute": "Face & Body",
    "rs_colour": "BLANK",
    "size": "One Size"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-22 20:06:51",
    "rs_sku": "NIK_B0802075816600002_TEAL",
    "rs_simple_sku": "NIK_B0802075816600002_TEAL-612MONTHS",
    "product_name": "Infants Teal Nike Air Blustery Set",
    "manufacturer": "Nike",
    "gender": "INFANTS",
    "product_size_attribute": "Sets",
    "rs_colour": "TEAL",
    "size": "6-12 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "STY_RN72UF5_PALEBLUE",
    "rs_simple_sku": "STY_RN72UF5_PALEBLUE-32",
    "product_name": "Ladies Blue Oversized Shirt",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "BLUE",
    "size": 32
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "STY_7955ADD_BLACK",
    "rs_simple_sku": "STY_7955ADD_BLACK-2XL",
    "product_name": "Mens Black Hooded Puffer Jacket",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "BLACK",
    "size": "2XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "STY_2O7KW7Y_WHITE",
    "rs_simple_sku": "STY_2O7KW7Y_WHITE-32",
    "product_name": "Ladies White Oversized Shirt",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Tops",
    "rs_colour": "WHITE",
    "size": 32
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "STY_63WB4NV_KHAKIGREEN",
    "rs_simple_sku": "STY_63WB4NV_KHAKIGREEN-XL",
    "product_name": "Mens Green Hooded Puffer Jacket",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "KHAKIGREEN",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "STY_63WB4NV_KHAKIGREEN",
    "rs_simple_sku": "STY_63WB4NV_KHAKIGREEN-L",
    "product_name": "Mens Green Hooded Puffer Jacket",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Outerwear",
    "rs_colour": "KHAKIGREEN",
    "size": "L"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "POP_4591M5N_BLACKANDWHITE",
    "rs_simple_sku": "POP_4591M5N_BLACKANDWHITE-36MONTHS",
    "product_name": "Black and White Infants Spots Onesie",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "3-6 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "POP_VVP6CB8_PALEBLUE",
    "rs_simple_sku": "POP_VVP6CB8_PALEBLUE-69MONTHS",
    "product_name": "Blue Infants Printed Sleepsuit",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "6-9 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-24 10:09:30",
    "rs_sku": "POP_BUF66EY_MULTICOLOUR",
    "rs_simple_sku": "POP_BUF66EY_MULTICOLOUR-36MONTHS",
    "product_name": "Multi-colour Infants Printed  Bodysuit",
    "manufacturer": "POP CANDY",
    "gender": "INFANTS",
    "product_size_attribute": "Tops",
    "rs_colour": "BLANK",
    "size": "3-6 Months"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-26 09:21:49",
    "rs_sku": "STY_I4IOC3N_WHITE",
    "rs_simple_sku": "STY_I4IOC3N_WHITE-XL",
    "product_name": "Mens White Woods Shirt",
    "manufacturer": "Style Republic",
    "gender": "MENS",
    "product_size_attribute": "Tops",
    "rs_colour": "WHITE",
    "size": "XL"
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-26 09:21:49",
    "rs_sku": "EUR_8134_GIRAFFE",
    "rs_simple_sku": "EUR_8134_GIRAFFE-32",
    "product_name": "Ladies Giraffe Trendy Bodysuit",
    "manufacturer": "Euro Sun",
    "gender": "LADIES",
    "product_size_attribute": "Swimwear",
    "rs_colour": "Giraffe",
    "size": 32
  },
  {
    "email": "suzanne.s@runwaysale.co.za",
    "ordered_at": "2018-11-26 09:21:49",
    "rs_sku": "STY_J63HRTI_BLACK",
    "rs_simple_sku": "STY_J63HRTI_BLACK-32",
    "product_name": "Black Frill Shirt Dress",
    "manufacturer": "Style Republic",
    "gender": "LADIES",
    "product_size_attribute": "Dresses",
    "rs_colour": "BLACK",
    "size": 32
  }
]